import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "landing page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-bahavior body-font" lang="en">
      <Toaster position="top-right" reverseOrder={false} />
      <body className="body-font">{children}</body>
    </html>
  );
}
